# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mwaacli < Formula
  desc "mwaacli is a CLI for interacting with MWAA"
  homepage "https://github.com/hupe1980/mwaacli"
  version "0.0.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/mwaacli/releases/download/v0.0.19/mwaacli_Darwin_x86_64.tar.gz"
      sha256 "c359f3ec1ff401e222a6e29d3ab9335f001071d01d09ab8c446c6247a111ae22"

      def install
        bin.install "mwaacli"
        bash_completion.install "completions/mwaacli.bash" => "mwaacli"
        zsh_completion.install "completions/mwaacli.zsh" => "_mwaacli"
        fish_completion.install "completions/mwaacli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/mwaacli/releases/download/v0.0.19/mwaacli_Darwin_arm64.tar.gz"
      sha256 "6780d70a788db7eeeeb7fb32b0d0a316041f0587af170a9494c2965b5e9c38c9"

      def install
        bin.install "mwaacli"
        bash_completion.install "completions/mwaacli.bash" => "mwaacli"
        zsh_completion.install "completions/mwaacli.zsh" => "_mwaacli"
        fish_completion.install "completions/mwaacli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hupe1980/mwaacli/releases/download/v0.0.19/mwaacli_Linux_x86_64.tar.gz"
        sha256 "717f4cf50621598a2101e880f3cc37b408872a2888aadf3503ebbc070f64f0b4"

        def install
          bin.install "mwaacli"
          bash_completion.install "completions/mwaacli.bash" => "mwaacli"
          zsh_completion.install "completions/mwaacli.zsh" => "_mwaacli"
          fish_completion.install "completions/mwaacli.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/hupe1980/mwaacli/releases/download/v0.0.19/mwaacli_Linux_armv6.tar.gz"
        sha256 "6eb3905e4f951fd4cdf3c994ae3c6648d2b92b141e245f2495dea09fd58de34c"

        def install
          bin.install "mwaacli"
          bash_completion.install "completions/mwaacli.bash" => "mwaacli"
          zsh_completion.install "completions/mwaacli.zsh" => "_mwaacli"
          fish_completion.install "completions/mwaacli.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hupe1980/mwaacli/releases/download/v0.0.19/mwaacli_Linux_arm64.tar.gz"
        sha256 "06379d6f4124ab471d9028083d3835c25d929c3d3b66c431825c18b3c5a5be94"

        def install
          bin.install "mwaacli"
          bash_completion.install "completions/mwaacli.bash" => "mwaacli"
          zsh_completion.install "completions/mwaacli.zsh" => "_mwaacli"
          fish_completion.install "completions/mwaacli.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/mwaacli -v"
  end
end
